### PR TITLE
.NET 5 upgrade 

### PR DESCRIPTION
**Pull request by MCCshreyas**
No description needed.

### CODE REVIEW

**Comment by jasontaylordev** [comment]
Thanks @MCCshreyas. I have retargeted your PR to the existing dotnet5 branch and approved. It looks like it's good to go. 👍

**Comment by MCCshreyas** [comment]
Yeah, thanks @jasontaylordev.
Yes, it's good to go to merge in main as well! 😅 😅

**Comment by jasontaylordev** [comment]
I want to get the other pull requests done first, so that I can do a final branch for .NET Core 3.1
Then we'll be good to go with .NET 5
I'll get back to it tomorrow night 😊

**Comment by MCCshreyas** [comment]
Sure!

**Pull request merged**
