### PR TITLE
Added dev env conditions for token in angular app

### PR DESCRIPTION
**Pull request by matt-goldman**
This pull request adds a condition to only show the JWT page in the menu in non-production environments. Also disables the route to the page if in production.

### CODE REVIEW

**Comment by matt-goldman** [comment]
Tested and working - just awaiting resolution of the CodeQL issue.

**Comment by jasontaylordev** [comment]
Thanks! 😊

**Comment by deceptiveSimplicity** [comment]
Hello, was adding package-lock.json to .gitignore intentional?

**Comment by matt-goldman** [comment]
> Hello, was adding package-lock.json to .gitignore intentional?

No, that was an error. I'll submit a fix.

**Pull request merged**
