### PR TITLE
FluentValidation Double hitting for each request

### PR DESCRIPTION
**Pull request by eldarmahmudov**

### CODE REVIEW

**Comment by eldarmahmudov** [comment]
On each request that has Validator validation occurs twice . By Validation Behaviour and By Fluent Validaton itself.I disabled Fluent Validation auto validation feature.

**Comment by neozhu** [comment]
> On each request that has Validator validation occurs twice . By Validation Behaviour and By Fluent Validaton itself.I disabled Fluent Validation auto validation feature.

if  FluentValidation  put into server side, Inside PipelineBehaviour  of  MediatR. reference. https://github.com/GetoXs/MediatR.Extensions.FluentValidation.AspNetCore.git.
I have a question what throw invalidate messages to client UI? client ui how to catch and prompt this error message?

**Comment by eldarmahmudov** [comment]
If you look at the CleanArchitecture Example code you will find the answer of you question

**Review by BretMishler — APPROVED** [review]
Solved the problem of repeated messages by fluent validation

**Comment by BretMishler** [comment]
@eldarmahmudov Actually I take back my approval. While your approach "fixed" my issue, the root of my problem was that my ValidationBehavior was pointing to FluentValidation, not the following

`using ValidationException = Cirrus.UploadApi.Application.Common.Exceptions.ValidationException;`

After the fix above, Im not able to repeat this.

**Pull request merged**
