### PR TITLE
Upgrade to .NET 7 GA & auto API client generation

### PR DESCRIPTION
**Pull request by ranjit-io**
- Upgrade .NET NuGet packages to 7.0.0
- Enables auto Web API client generation for Angular

### CODE REVIEW

**Comment by misha130** [comment]
Was the generation removed on purpose and now readded or was it temporarly turned off?

**Comment by fverne** [comment]
Right now this gives build errors one doesn't have the aspnetcore 6 runtime installed, as both nswag.json and WebUI.csproj use nswag for 6, and not 7.

**Comment by ranjit-io** [comment]
> This gives build errors if one doesn't have the aspnetcore 6 runtime installed, as both nswag.json and WebUI.csproj use nswag for 6, and not 7.

Good pickup! Updated the PR.

**Review by jasontaylordev — DISMISSED** [review]

**Comment by jasontaylordev** [comment]
Thanks @ranjit-io - please can you update global.json as well. It still specifies the net7.0.

**Comment by ranjit-io** [comment]
> Thanks @ranjit-io - please can you update global.json as well. It still specifies the net7.0.

Hi Jason, I have updated the global.json file but the build is still failing in my fork due to Nswag. Will try to fix it.

**Comment by misha130** [comment]
I had the same issue and I just opted out to use swagger instead of nswag

**Comment by ranjit-io** [comment]
I have changed the NSwag build task to only execute in development/debug mode. Otherwise, a valid license is required for Identity Server - unsure why

**Review by jasontaylordev — DISMISSED** [review]
Thanks, much appreciated. 💙

**Review by jasontaylordev — APPROVED** [review]

**Comment by jasontaylordev** [comment]
Thanks for your contribution! I had intended to merge this tonight but accidentally merged a newer PR with the same changes. Never code tired. 🙁

**Pull request closed without merging**
