### PR TITLE
Using new extension method for struct values

### PR DESCRIPTION
**Pull request by kibernetik542**
Idea is instead of all time using chain repeated helper functions from FluentValidation using new extension methods, and advantage is does not matter int, decimal, float or double we can use for all of them, and it is also nullable version.

### CODE REVIEW

**Comment by neozhu** [comment]
how to use it, please give me a sample

**Comment by kibernetik542** [comment]
> how to use it, please give me a sample

```
public class Test
{
    public decimal? Price { get; set ; }
    public int? Quantity { get; set ; }
    public bool Enabled { get; set; }
    public double Sale { get; set; }
}
```

```
public class TestValidator : AbstractValidator<Test>
{
   public TestValidator()
   {
        RuleFor(x => x.Price).RangeWithWhen("Price", 1, 300, c => c.Price is not null);
        RuleFor(x => x.Quantity).RangeWithWhen("Quantity", 1,10, c => c.Enabled);
        RuleFor(x => x.Sale).RangeWithWhen("Sale", 10, 30, c => !c.Enabled);
   }
}
```

In my extension it is When condition, but for sure we can create however we want, advantage of this we are using for all struct based values same extension method

**Comment by neozhu** [comment]
> 
I got, Thanks

**Comment by IvanAntipov** [comment]
Does it make sense to propose this extension to FluentValidation repository? 
As far as I understand AIM of  CleanArchitecture repository is to provide a template with a skeleton project with a best-practice structure, for learning and/or demo and/or prototyping purposes.

In my opinion, this extension will increase, a little bit the learning curve, especially for people who are not familiar with `FluentValidation`, because this introduces an additional level in the call chain. 
 
I agree that `RangeWithWhen ` is simpler to read than `.InclusiveBetween(..).With Message().When()`, but I would prefer to have it out of the box with `FluentValidation` package.

**Comment by kibernetik542** [comment]
In the end it is nothing new for FluentValidation, just extension method with ready chain methods. 
As it is FluentValidation usage in Clean Architecture skeleton. I think it makes sense propose handy extension methods. 

I can give one example which is automapper. It is extension method using ProjectTo for pagination and reflection for IMapFrom in this repository. 

IMHO related packages can be simplified witg suggestions.

**Comment by jasontaylordev** [comment]
HI @kibernetik542. Thanks for the PR however I've decided not to merge in the interest of keeping the template as simple as possible. Thanks anyway and happy coding! 😀

**Pull request closed without merging**
