### PR TITLE
Replaced DateTimeService with System.TimeProvider

### PR DESCRIPTION
**Pull request by tonven**
Starting from .NET 8 there is an inbuild TimeProvider Class which can be used as an abstractrion over DateTime. https://learn.microsoft.com/en-us/dotnet/api/system.timeprovider?view=net-8.0

### CODE REVIEW

**Comment by neozhu** [comment]
I think it's better to save in UTC time, and convert to local time for display when outputting.

**Comment by Tonvengo** [comment]
> I think it's better to save in UTC time, and convert to local time for display when outputting.

I agree. I was also thinking about changing Created and LastModified to DateTimeOffset and saving it to UTC time.

@jasontaylordev what do you think?

**Comment by jasontaylordev** [comment]
> > I think it's better to save in UTC time, and convert to local time for display when outputting.
> 
> I agree. I was also thinking about changing Created and LastModified to DateTimeOffset and saving it to UTC time.
> 
> @jasontaylordev what do you think?

I agree, thanks for the contribution. 🙂

**Comment by jasontaylordev** [comment]
Thanks again @tonven. Once the final changes come through, I'll review and merge.

**Comment by rlarno** [comment]
If you change to using UTC, I suggest to also reflect that to the property names `CreatedUTC` and `LastModifiedUTC`

What these values need to contain so depend on the usecase. If these properties are for 'operational' reasons, UTC is the best value, as you can correlate typically with server logs which also (should) have UTC. If these values are to be used to define when the user created/modified the TodoItem, a full `DateTimeOffset` should be used, unless you are sure to always be operating in a single timezone.

**Comment by jasontaylordev** [comment]
Closing due to inactivity, feel free to raise again.

**Pull request closed without merging**
