### PR TITLE
✨ Implement API only option in template

### PR DESCRIPTION
**Pull request by Lanz86**
API only template version #776
implemented flag apiOnly

the command created solution with Angular

<code>
dotnet new ca-sln
</code>

Create solution without Angular
<code>
dotnet new ca-sln --apiOnly=true 
</code>

### CODE REVIEW

**Comment by JohanHeyvaert** [comment]
I suppose the nswag typescript client generation needs to be deactivated too. (if not already done)

**Comment by Lanz86** [comment]
> I suppose the nswag typescript client generation needs to be deactivated too. (if not already done)
Yes is implemented you find directive in src/WebUI/nswag.json line 63 - 128

**Comment by jasontaylordev** [comment]
@Lanz86 thank you for the contribution. The updated template supports both Angular and React, but not API only. I think we are now in a good position to implement API only too. The approach will need to change. If you look at the new [template.json](https://github.com/jasontaylordev/CleanArchitecture/blob/main/.template.config/template.json) you can see the following parameter:

```json
    "clientFramework": {
      "type": "parameter",
      "datatype": "choice",
      "choices": [
        {
          "choice": "angular",
          "description": "Use Angular"
        },
        {
          "choice": "react",
          "description": "Use React"
        }
      ],
      "defaultValue": "angular",
      "description": "The type of client framework to use"
    },
```

I think API only can be implemented by adding the choice **none**, for example:

```json
        {
          "choice": "none",
          "description": "Use API only"
        },
```

What do you think? Do you want to tackle this change?

**Comment by Lanz86** [comment]
Ok @jasontaylordev sounds good. 
I will take care of it.

**Comment by Lanz86** [comment]
Closed this PR and created new to support a none choice in clientFramework symbols https://github.com/jasontaylordev/CleanArchitecture/pull/886

**Pull request closed without merging**
